### PR TITLE
Add test coverage, document return value on failure, improve package.json

### PR DESCRIPTION
**Pull request by markstos**

### CODE REVIEW

**Comment by eivindfjeldstad** [comment]
Thank you! This pull request does too much though. I like some of the changes you've made, but I'm not going to merge this as-is. If you want something specific, please submit a smaller, more focused pull request:)

**Comment by markstos** [comment]
Without feedback on which commits you are interested in and which you aren't, it's not worth my time guessing what you are interested in merging and what you aren't. I was hoping to collaborate, but it looks my time will be better spent contributing elsewhere.

**Comment by eivindfjeldstad** [comment]
The only thing I'd object to is the changes to package.json and removing the Makefile. The rest I'm okay with. It's MIT licensed, so if you want to maintain your own fork you're more than welcome to:)

**Comment by markstos** [comment]
OK. The Makefile is not necessary-- "npm test" does the same thing now, but
that's your choice.

You are welcome to use `git cherry-pick` if you want to apply some commits
and not others.

On Tue, Sep 22, 2015 at 10:40 AM, Eivind Fjeldstad <notifications@github.com
> wrote:

> The only thing I'd object to is the changes to package.json and removing
> the Makefile. The rest I'm okay with. It's MIT licensed, so if you want to
> maintain your own fork you're more than welcome to:)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/eivindfjeldstad/to-coordinates/pull/1#issuecomment-142308082>
> .
>



-- 
    Mark Stosberg
    Senior Systems Engineer
    RideAmigos

**Comment by markstos** [comment]
There are nearly 200,000 npm modules now, and the keywords I added to
package.json will help this project be found.

The `homepage` link I added is also common and helps people easily link to
the Github site from the npmjs.org site.

**Pull request closed without merging**
